# Generated by Django 3.0.4 on 2020-07-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock', models.IntegerField(blank=True, default=0, null=True)),
                ('paper', models.IntegerField(blank=True, default=0, null=True)),
                ('scissors', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pScore', models.IntegerField(blank=True, default=0, null=True)),
                ('cScore', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
