# Generated by Django 3.0.4 on 2020-07-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200703_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerStat',
            new_name='Stat',
        ),
    ]
