# Generated by Django 3.0.4 on 2020-07-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200705_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='tie',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
